#! /bin/bash
#
# This is a simple kernel hook to fix the grub bootloader when a new kernel is installed
# And hopefully when it is initially installed on a new system
#

printf "Running grub fix.."

fix-grub

# Success!
exit 0
